version: '3.8'

services:
  redis:
    image: redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    networks:
      - backend
  nodejs:
    build: .
    ports:
      - '4000:4000'
    networks:
      - backend
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - '80:80'
    depends_on:
      - nodejs
    networks:
      - backend
networks:
  backend:
